import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.models.agents import AgentName, InteractionStatus, SessionStatus, SessionType


class AgentSessionCreate(BaseModel):
    """
    Input schema for initiating an agent session.
    Requires at least one context parameter (topic_id, content_id, or user_inquiry).
    """
    session_type: SessionType
    topic_id: Optional[uuid.UUID] = None
    content_id: Optional[uuid.UUID] = None
    user_inquiry: Optional[str] = None

    @model_validator(mode="after")
    def validate_learning_context(self) -> "AgentSessionCreate":
        has_inquiry = bool(self.user_inquiry and self.user_inquiry.strip())
        if not (self.topic_id or self.content_id or has_inquiry):
            raise ValueError(
                "At least one learning context must be provided: topic_id, content_id, or user_inquiry."
            )
        return self


class AgentSessionResponse(BaseModel):
    """Safe response schema for an agent session."""
    id: uuid.UUID
    learner_profile_id: uuid.UUID
    session_type: SessionType
    status: SessionStatus
    user_inquiry: Optional[str] = None
    topic_id: Optional[uuid.UUID] = None
    content_id: Optional[uuid.UUID] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class LearnerContextFrame(BaseModel):
    """
    Evidence-based learner context synthesized from actual learner data.
    Strictly represents observed metrics and user-configured preferences without clinical inferences.
    """
    learner_level: str
    overall_mastery: float = Field(ge=0.0, le=1.0)
    weak_topics: List[str] = Field(default_factory=list)
    strong_topics: List[str] = Field(default_factory=list)
    recent_performance_summary: str
    learning_preferences: Dict[str, Any] = Field(default_factory=dict)
    accessibility_preferences: Dict[str, Any] = Field(default_factory=dict)
    recommended_difficulty: str
    evidence_based_learning_gaps: List[str] = Field(
        default_factory=list,
        description="Factual observations of specific skill gaps supported by practice/assessment data."
    )
    prerequisite_blockers: List[str] = Field(
        default_factory=list,
        description="Prerequisite topics with low mastery impacting current performance."
    )
    adaptation_parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Concrete pedagogical adaptation parameters (e.g. pace, step size, example density)."
    )


class WorkedExample(BaseModel):
    """Structured representation of an educational worked example."""
    title: str
    problem: str
    solution_steps: List[str] = Field(default_factory=list)
    explanation: Optional[str] = None


class ContentAdaptationResult(BaseModel):
    """Result of content adaptation agent specialized for learner needs."""
    title: str
    adapted_explanation: str
    key_concepts: List[str] = Field(default_factory=list)
    worked_examples: List[WorkedExample] = Field(default_factory=list)
    scaffolding_steps: List[str] = Field(default_factory=list)
    complexity_level: str
    adaptation_rationale: str


class AssessmentQuestionResult(BaseModel):
    """Formative assessment question generated by assessment agent."""
    question: str
    question_type: str = "multiple_choice"
    options: List[str] = Field(default_factory=list)
    correct_answer: str
    explanation: str
    difficulty: str
    targeted_learning_gap: Optional[str] = None
    distractor_rationales: Dict[str, str] = Field(
        default_factory=dict,
        description="Rationales for why common distractors/misconceptions might be selected."
    )


class AssessmentAgentOutput(BaseModel):
    """Container schema for structured LLM formative assessment question generation."""
    questions: List[AssessmentQuestionResult] = Field(default_factory=list)


class AccessibilityAdaptationResult(BaseModel):
    """Accessibility adjustments and alternative representations for content."""
    accessible_content: str
    plain_language_summary: str
    content_structure: List[str] = Field(default_factory=list)
    recommended_presentation: Dict[str, Any] = Field(
        default_factory=dict,
        description="Recommended presentation settings (e.g. high contrast, screen reader order, simplified layout)."
    )
    accessibility_rationale: str


class AgentInteractionResult(BaseModel):
    """Individual agent execution audit entry."""
    agent_name: AgentName
    status: InteractionStatus
    output: Dict[str, Any] = Field(default_factory=dict)
    latency_ms: int = 0
    error_message: Optional[str] = None


class MultiAgentResponse(BaseModel):
    """
    Unified multi-agent response coordinated across specialized sub-agents.
    Accommodates partial or full agent invocations based on session type.
    """
    session_id: uuid.UUID
    learner_context: LearnerContextFrame
    adapted_content: Optional[ContentAdaptationResult] = None
    assessment: Optional[List[AssessmentQuestionResult]] = None
    accessibility_adaptation: Optional[AccessibilityAdaptationResult] = None
    agent_results: List[AgentInteractionResult] = Field(default_factory=list)
    execution_summary: str


class RuleBasedComparisonResult(BaseModel):
    """Comparison between deterministic Phase 2 rule engine and Phase 3 multi-agent intelligence."""
    rule_based_output: Dict[str, Any]
    multi_agent_output: Dict[str, Any]
    comparison_summary: str
    learner_rating: Optional[int] = Field(default=None, ge=1, le=5)


class AgentComparisonEvaluationCreate(BaseModel):
    """Creation payload for agent comparison evaluation."""
    session_id: uuid.UUID
    rule_based_output: Optional[Dict[str, Any]] = None
    multi_agent_output: Optional[Dict[str, Any]] = None
    learner_rating: Optional[int] = Field(default=None, ge=1, le=5)
    notes: Optional[str] = None


class AgentComparisonEvaluationResponse(BaseModel):
    """Response payload for agent comparison evaluation."""
    id: uuid.UUID
    session_id: uuid.UUID
    rule_based_output: Dict[str, Any]
    multi_agent_output: Dict[str, Any]
    learner_rating: Optional[int] = None
    notes: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
